export default {
  cart: [],
  buyer: [],
  orders: [],
  products: [
    {
      id: "1",
      image: "https://arepa.s3.amazonaws.com/mug.png",
      // image: "/assets/clothes/1.jpg",
      title: "Camiseta",
      price: 25,
      size: [
        {
          small: "s",
          medium: "m",
          large: "l",
          extra: "xl",
        },
      ],
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "2",
      image: "https://arepa.s3.amazonaws.com/mug.png",
      title: "Camiseta",
      price: 15,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "3",
      image: "https://arepa.s3.amazonaws.com/pin.png",
      title: "Camiseta",
      price: 20,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "4",
      image: "https://arepa.s3.amazonaws.com/stickers1.png",
      title: "Chaqueta",
      price: 230,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "5",
      image: "https://arepa.s3.amazonaws.com/stickers2.png",
      title: "Chaqueta",
      price: 200,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "6",
      image: "https://arepa.s3.amazonaws.com/hoodie.png",
      title: "Hoodie",
      price: 80,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "7",
      image: "https://arepa.s3.amazonaws.com/hoodie.png",
      title: "Abrigo",
      price: 170,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "8",
      image: "https://arepa.s3.amazonaws.com/hoodie.png",
      title: "Blusa",
      price: 25,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "9",
      image: "https://arepa.s3.amazonaws.com/hoodie.png",
      title: "Blusa",
      price: 30,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: "10",
      image: "https://arepa.s3.amazonaws.com/hoodie.png",
      title: "Abrigo",
      price: 160,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
  ],
};
